app = 'relens-ig-scraper'
primary_region = 'cdg'

[build]
dockerfile = 'Dockerfile'

[build.args]
ENV = 'release'

[[vm]]
memory = '2gb'
cpu_kind = 'performance'
cpus = 1

[[restart]]
policy = 'never'
